name: ci

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    uses: tty-pt/ci/.github/workflows/all-in-one.yml@main
    with:
      name: libqgl
      deps: "libqmap,libglfw3-dev,libpng-dev,libglew-dev"
      deps_apk: "libqmap,glfw-dev,libpng-dev,glew-dev"
      deps_pacman: "libqmap,glfw,libpng,glew"
      deps_rpm: "libqmap,glfw-devel,libpng-devel,glew-devel"
      deps_brew: "libqmap,glfw,libpng"
      deps_openbsd: "libqmap,libqsys,glfw,png,glew"
      deps_pacman_mingw: "mingw-w64-libqmap,mingw-w64-glfw,mingw-w64-libpng,mingw-w64-glew"
    secrets:
      HOST: ${{ secrets.OPENBSD_HOST }}
      USER: ${{ secrets.OPENBSD_USER }}
      SSH_KEY: ${{ secrets.OPENBSD_SSH_KEY }}
      GPG_PRIVATE_KEY: ${{ secrets.OPENBSD_GPG_PRIVATE_KEY }}
      GPG_PASSPHRASE: ${{ secrets.OPENBSD_GPG_PASSPHRASE }}
      GPG_KEYID: ${{ secrets.OPENBSD_GPG_KEY_ID }}
      ABUILD_PRIVATE_KEY: ${{ secrets.ABUILD_PRIVATE_KEY }}
      ABUILD_PUBLIC_KEY: ${{ secrets.ABUILD_PUBLIC_KEY }}
      TAP_TOKEN: ${{ secrets.TAP_TOKEN }}
