name: CI Test

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Run shared CI Test Action
        uses: tty-pt/ci/test@main
        with:
          deps: "libqmap,libglfw3-dev,libpng-dev,libglew-dev,libxxhash-dev"
